-- Descrição dos usuários
SELECT
    U.ID_USUARIO,
    U.NOME_USUARIO,
    P.DESCRICAO    AS PERFIL_DESCRICAO
FROM
    USUARIOS U
    LEFT JOIN PERFIS P ON U.ID_USUARIO = P.ID_USUARIO;

-- Quem criou o grupo
SELECT
    G.ID_GRUPO,
    G.NOME_GRUPO,
    U.NOME_USUARIO AS CRIADOR
FROM
    GRUPOS   G
    JOIN USUARIOS U ON G.ID_CRIADOR = U.ID_USUARIO;

-- Quem o usuário (x) está seguindo
SELECT
    C.ID_SEGUIDOR,
    C.ID_SEGUIDO,
    U.NOME_USUARIO AS SEGUIDO_NOME
FROM
    CONEXOES C
    JOIN USUARIOS U ON C.ID_SEGUIDO = U.ID_USUARIO
WHERE
    C.ID_SEGUIDOR = 1;

-- Chat privado entre 2 usuários
SELECT
    M.ID_MENSAGEM,
    U1.NOME_USUARIO   AS REMETENTE,
    U2.NOME_USUARIO   AS DESTINATARIO,
    M.CONTEUDO,
    M.STATUS_MENSAGEM,
    M.DATA_ENVIO
FROM
    MENSAGENS M
    JOIN CONVERSAS C
    ON M.ID_CONVERSA = C.ID_CONVERSA
    JOIN USUARIOS U1
    ON M.ID_REMETENTE = U1.ID_USUARIO
    JOIN USUARIOS U2
    ON ( (C.ID_REMETENTE = U1.ID_USUARIO
    AND C.ID_DESTINATARIO = U2.ID_USUARIO)
    OR (C.ID_REMETENTE = U2.ID_USUARIO
    AND C.ID_DESTINATARIO = U1.ID_USUARIO) )
WHERE
    (C.ID_REMETENTE = 11
    AND C.ID_DESTINATARIO = 12)
    OR (C.ID_REMETENTE = 12
    AND C.ID_DESTINATARIO = 11)
ORDER BY
    M.DATA_ENVIO;

-- Quais grupos determinado usuário está incluido
SELECT
    U.NOME_USUARIO,
    G.ID_GRUPO,
    G.NOME_GRUPO,
    G.DESCRICAO,
    G.DATA_CRIACAO
FROM
    MEMBROS M
    JOIN GRUPOS G ON M.ID_GRUPO = G.ID_GRUPO
    JOIN USUARIOS U ON M.ID_USUARIO = U.ID_USUARIO
WHERE
    M.ID_USUARIO = 1;